name: Discord Notification

on:
  page_build: # index.html 등 소스 변경으로 인한 자동 빌드 시 트리거

jobs:
  notify-success:
    runs-on: ubuntu-latest
    if: github.event.build.status == 'built'
    steps:
      - name: Get Current Time
        run: echo "CURRENT_TIME=$(TZ=Asia/Seoul date +'%m.%d %H:%M')" >> $GITHUB_ENV

      - name: 🟢 Notify Discord on Success
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "embeds": [{
                   "title": "HTML 배포 결과",
                   "description": "🌐 [${{ github.repository }}] index.html 배포 **${{ job.status }}**! (${{ env.CURRENT_TIME }})",
                   "color": 5763719
                 }]
               }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
