name: Discord Notification

on:
  deployment_status:

jobs:
  notify-discord:
    if: github.event.deployment.environment == 'github-pages'
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Time
        run: echo "CURRENT_TIME=$(TZ=Asia/Seoul date +'%m.%d %H:%M')" >> $GITHUB_ENV

      - name: Notify Discord
        run: |
          # 깃허브 배포 상태(success 또는 failure)에 따라 분기
          if [ "${{ github.event.deployment_status.state }}" = "success" ]; then
            COLOR=5763719
            EMOJI="🌐"
          else
            COLOR=15548997
            EMOJI="🚨"
          fi

          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "embeds": [{
                   "title": "HTML 배포 결과",
                   "description": "'"$EMOJI"' [${{ github.repository }}] index.html 배포 **${{ github.event.deployment_status.state }}** (${{ env.CURRENT_TIME }})",
                   "color": '"$COLOR"'
                 }]
               }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
